### ISSUE TITLE
关于crc校验的问题

### ISSUE THREAD

**Issue by arui3015** [ykrenz/fastdfs-client-spring-boot-starter#4]
我这边本地计算的 crc和 fastdfs查询的crc不同，经过convertUnsigned转换以后仍然不相等，请问大佬知道是啥情况吗？或者是某个版本有问题，我们使用的版本是fastdfs 是5.11

**Comment by ykrenz** [comment]
可否提供计算crc代码

**Comment by arui3015** [comment]
> 

大佬回复了，太好了，我就是使用的是你的客户端代码里面的Crc32工具类计算的，这样计算出来crc值和 fileInfo里面的crd32都不相等,convertUnsigne以后还是不相等
long crc321 = Crc32.file(sampleFile);
        System.out.println(fileInfo.getCrc32());
        System.out.println(Crc32.convertUnsigned(fileInfo.getCrc32()));

**Comment by ykrenz** [comment]
可以提供一下文件吗

**Comment by arui3015** [comment]
> 可以提供一下文件吗

大佬，问题已经确认了，fastdfs5.11的问题，我重新部署了6.0.8问题就解决了，你的客户端程序没有问题的。

**Comment by ykrenz** [comment]
感谢 可参考https://github.com/happyfish100/fastdfs/blob/master/HISTORY
5.1.2版本修复了该问题 correct CRC32, you must upgrade libfastcommon to V1.38 or later
